version: "3"

services:
  web:
    build: .
    container_name: api-server
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: api-db
    image: postgres:9.6
    expose:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pg_data:
  pg_backups:
