version: "3"

services:
  nginx:
    build: ./config/nginx
    container_name: api-nginx
    depends_on:
      - web
    links:
      - web:web
    ports:
      - 3000:3000
    restart: unless-stopped

  web:
    build: .
    container_name: api-server
    depends_on:
      - cache
    links:
      - cache:cache
    ports:
      - 8000:8000
    restart: unless-stopped

  cache:
    image: redis
    container_name: api-cache
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    restart: unless-stopped

volumes:
  cache_data:
