URL = {
    'user_create_url': '/api/v1/accounts/user/',
    'user_detail_url': '/api/v1/accounts/user/{}/',
    'get_jwt_token':'/api/v1/accounts/api-token-auth/',
    'profile_get_post':'/api/v1/accounts/profile/',
    'user_put_delete':'/api/v1/accounts/user/{}/',
    'profile_put':'/api/v1/accounts/profile/{}/',
    'sentence_get_post':'/api/v1/services/sentence/',
    'sentence_put_delete':'/api/v1/services/sentence/1/',
    'state_get_post':'/api/v1/services/state/',
    'state_put_delete':'/api/v1/services/state/1/',
    'word_get_post':'/api/v1/services/word/',
    'word_put_delete':'/api/v1/services/word/1/',
    'text_get_post':'/api/v1/services/text/',
    'text_put_delete':'/api/v1/services/text/1/',
}
